/*
 * LED_MATRIX_config.h
 *
 *  Created on: 16 Jan 2018
 *      Author: Nayir
 */

#ifndef LED_MATRIX_CONFIG_H_
#define LED_MATRIX_CONFIG_H_

#define u8_LED_MATRIX_PIN_COL_0 DIO_u8_PIN_0
#define u8_LED_MATRIX_PIN_COL_1 DIO_u8_PIN_1
#define u8_LED_MATRIX_PIN_COL_2 DIO_u8_PIN_2
#define u8_LED_MATRIX_PIN_COL_3 DIO_u8_PIN_3
#define u8_LED_MATRIX_PIN_COL_4 DIO_u8_PIN_4
#define u8_LED_MATRIX_PIN_COL_5 DIO_u8_PIN_5
#define u8_LED_MATRIX_PIN_COL_6 DIO_u8_PIN_6
#define u8_LED_MATRIX_PIN_COL_7 DIO_u8_PIN_7

#define u8_LED_MATRIX_PIN_ROW_0 DIO_u8_PIN_24
#define u8_LED_MATRIX_PIN_ROW_1 DIO_u8_PIN_25
#define u8_LED_MATRIX_PIN_ROW_2 DIO_u8_PIN_26
#define u8_LED_MATRIX_PIN_ROW_3 DIO_u8_PIN_27
#define u8_LED_MATRIX_PIN_ROW_4 DIO_u8_PIN_28
#define u8_LED_MATRIX_PIN_ROW_5 DIO_u8_PIN_29
#define u8_LED_MATRIX_PIN_ROW_6 DIO_u8_PIN_30
#define u8_LED_MATRIX_PIN_ROW_7 DIO_u8_PIN_31

#define u8_LED_MATRIX_POV_DELAY 2

#endif /* LED_MATRIX_CONFIG_H_ */
